
#export PRJROOT:=$(PWD)
export PRJROOT:=$(shell pwd)

include $(PRJROOT)/Rules.mak
-include $(PRJROOT)/.config

#export PATH			:= $(TOOLCHAIN_DIR)/bin:$(shell echo $$PATH)
CONFIG_DIR			:= $(PRJROOT)/config
###KERNEL_SRC_DIR := $(PRJROOT)/$(call path-for,kernel)/$(patsubst "%",%,$(KERNEL_SRC))
MODULES :=
hide := @
err := -
include mkfile/pathmap.mk
include mkfile/toolchain.mk

#check_test:
#	#if [ $(call test) ] ; then
#	@if [ 0 == 1 ] ; then \
#		echo shit; \
#	fi
#
##define test
##	if [ 1 ] ; then \
##		true; \
##	fi
##endef
#define test
#$(if $(0), 0, 0)
#endef
