#
# Makefile for the Create DSP 5502 device drivers.
#
# 15 Aug 2000, Christoph Hellwig <hch@infradead.org>
# Rewritten to use lists instead of if-statements.
#



obj-$(CONFIG_CREATOR_PXA270_DSP_5502)			+= creator-pxa270-dsp-5502.o
creator-pxa270-dsp-5502-objs := creator-pxa270-dsp5502.o halhpiapi.o halhpisys.o 

